---
title: "VST_counts"
output: html_notebook
---

# ```{r setup, include=FALSE, dev="CairoPNG"}
# library(Cairo)
# Sys.setenv("DISPLAY"=":0")
# knitr::opts_chunk$set(echo = TRUE, dev="CairoPNG")
# options(bitmapType='cairo')
# getOption('bitmapType')
# ```

```{r}
library(ggplot2,quietly=T,warn.conflicts = F)
library(tidyverse,quietly=T,warn.conflicts = F)
library(DESeq2,quietly=T,warn.conflicts = F)
library(patchwork,quietly=T,warn.conflicts = F)
library(vsn)
library(MASS)
```

#Raw counts data transformations (vsc, log)
Load tpm.df, merged estimated counts table (both int and numeric)
```{r}
#Load tpm.df for later use with tpm filtering functions 
full_ac_data_dir = "formatted_output/4th_trial/full/E7"
AC_tag = "E7"

tpm_fpath = sprintf("%s/column_filtered_tpm.csv",full_ac_data_dir)
mc_int_fpath = sprintf("%s/abundance_corrected_count_int.csv",full_ac_data_dir)
mc_float_fpath = sprintf("%s/abundance_corrected_count.csv",full_ac_data_dir)

tpm.df <- read.csv(tpm_fpath,row.names="target_id")
#Load merged counts 
merged_counts_int.df <- read.csv(mc_int_fpath,row.names="target_id")
mc_int_matrix <- data.matrix(merged_counts_int.df)
mode(mc_int_matrix) <- "integer"

merged_counts_num.df <- read.csv(mc_float_fpath,row.names="target_id")
mc_num_matrix = data.matrix(merged_counts_num.df)
```

1. VST of int version of full merged counts
2. log transform of numeric full merged counts 
```{r}
PSEUDOCOUNT = 0.1
transformed_dir = "formatted_output/4th_trial/transformed"
dir.create(file.path(getwd(),transformed_dir),showWarnings = FALSE)

TRANSFORM_FULL_DATA <- FALSE 
if (TRANSFORM_FULL_DATA) {
  vsc.df <- as.data.frame(vst(mc_int_matrix))
  vsc_fpath = sprintf("%s/full_merged_vst.csv",transformed_dir)
  write.csv(vsc.df,vsc_fpath,quote=FALSE)
  
  log_mc = log(mc_num_matrix + PSEUDOCOUNT)
  log_mc.df <- as.data.frame(log_mc)
  log_mc_fpath = sprintf("%s/full_merged_log.csv",transformed_dir)
  write.csv(log_mc.df,log_mc_fpath)
}
```
Plot raw, tpm, vst, and log histograms 
```{r}
PLOT_RAW_HISTS <- TRUE
if (PLOT_RAW_HISTS) {
  if (TRANSFORM_FULL_DATA){
    tpm_hist <- ggplot(gather(tpm.df, cols, value), aes(x = value)) + 
       geom_histogram(bins=50) 
    tpm_hist + ggtitle("TPM Histogram") + theme(plot.title = element_text(hjust = 0.5))
    
    vst_hist <- ggplot(gather(vsc.df, cols, value), aes(x = value)) + 
           geom_histogram(bins=50) 
    vst_hist + ggtitle("VST Estimated Counts Histogram") + theme(plot.title = element_text(hjust = 0.5))
  }
  
  log_mc = log(mc_num_matrix + PSEUDOCOUNT)
  log_mc.df <- as.data.frame(log_mc)
  log_hist <- ggplot(gather(log_mc.df, cols, value), aes(x = value)) + 
         geom_histogram(bins=50) 
  log_hist + ggtitle("Log Counts Histogram") + theme(plot.title = element_text(hjust = 0.5))
  print(log_hist)
  
  log_mc_int = log(mc_int_matrix + PSEUDOCOUNT)
  log_mc_int.df <- as.data.frame(log_mc_int)
  log_hist_int <- ggplot(gather(log_mc_int.df, cols, value), aes(x = value)) + 
         geom_histogram(bins=50) 
  log_hist_int + ggtitle("Log Int Counts Histogram") + theme(plot.title = element_text(hjust = 0.5))
  print(log_hist_int)
}
```
Tpm and prevalence filtering functions
```{r}
#' Returns a vector of gene loci meeting tpm and prevalence thresholds
#' @param tpm.df = locus rows x sample columns
#' @param inp_threshold = threshold of tpm
#' @param inp_prevalence = the proportion of samples that are above inp_threshold
#' @param CECAL_ONLY c(TRUE,FALSE), if TRUE will only use cecal contents for tpm and prevalence filtering; default FALSE 
get_filtered_gene_vec <- function(tpm.df, inp_threshold, inp_prevalence,CECAL_ONLY=FALSE) {
  
  if (CECAL_ONLY) { 
    CECAL_COL_RE = "cecal"
    cecal_samples <- grep(CECAL_COL_RE, colnames(tpm.df)) 
    tpm.df <- dplyr::select(tpm.df,cecal_samples)
  }
  num_samples <- ncol(tpm.df)
  genes_passing <- rownames(data.frame(logic = rowSums(tpm.df > inp_threshold) > num_samples*inp_prevalence) %>% filter(logic == TRUE))
  return(genes_passing)
  
}
get_prevotella_filtered_gene_vec <- function(tpm.df, inp_threshold, inp_prevalence,CECAL_ONLY=FALSE) {
    #' @param tpm.df locus rows x sample columns
    #' @param inp_threshold threshold of tpm
    #' @param inp_prevalence the proportion of samples that are above inp_threshold
    #' @param CECAL_ONLY TRUE,FALSE; default FALSE. If TRUE, only cecal samples (ie columns containing "cecal") will be used to determine if loci meet tpm and prevalence thresholds. 
  PREVOTELLA_ROW_RE <- "(NJCFFJJN)|(NBCBLOMG)"
  PREVOTELLA_COL_RE <- "1C"
  
  if (CECAL_ONLY) { 
    CECAL_COL_RE = "cecal"
    cecal_samples <- grep(CECAL_COL_RE, colnames(tpm.df)) 
    tpm.df <- dplyr::select(tpm.df,cecal_samples)
  }
  
  num_samples <- ncol(tpm.df)
  prevotella_samples <- grep(PREVOTELLA_COL_RE, colnames(tpm.df))
  prevotella.df <- dplyr::select(tpm.df,prevotella_samples)
  num_prev_samples <- ncol(prevotella.df)
  #Logic has two cases: 
  #1.number of samples in tpm.df which have tpm > inp_threshold is 
  #greater than number of samples * inp_prevalence
  #2.Prevotella case: number of prevotella containing (1C) samples > inp_threshold is
  #greater than numper of prevotella samples AND row corresponds to prevotella locus
  genes_passing <- rownames(data.frame(logic = ((rowSums(tpm.df > inp_threshold) > num_samples*inp_prevalence) | (rowSums(prevotella.df > inp_threshold) >num_prev_samples*inp_prevalence & (grepl(PREVOTELLA_ROW_RE, row.names(tpm.df)))))) %>% filter(logic == TRUE))
  return(genes_passing)
}
```

```{r}
get_non_prevotella_filtered_gene_vec <- function(tpm.df, inp_threshold, inp_prevalence,CECAL_ONLY=FALSE) {
    #' @param tpm.df locus rows x sample columns
    #' @param inp_threshold threshold of tpm
    #' @param inp_prevalence the proportion of samples that are above inp_threshold
    #' @param CECAL_ONLY TRUE,FALSE; default FALSE. If TRUE, only cecal samples (ie columns containing "cecal") will be used to determine if loci meet tpm and prevalence thresholds. 
    #' @return genes_passing Vector of locus tags corresponding to loci which 
    #' are NOT from Prevotella species and also meet the above threshold and 
    #' prevalence criteria 
  PREVOTELLA_ROW_RE <- "(NJCFFJJN)|(NBCBLOMG)"
  PREVOTELLA_COL_RE <- "1C"
  
  if (CECAL_ONLY) { 
    CECAL_COL_RE = "cecal"
    cecal_samples <- grep(CECAL_COL_RE, colnames(tpm.df)) 
    tpm.df <- dplyr::select(tpm.df,cecal_samples)
  }
  num_samples <- ncol(tpm.df)
  prevotella_samples <- grep(PREVOTELLA_COL_RE, colnames(tpm.df))
  prevotella.df <- dplyr::select(tpm.df,prevotella_samples)
  num_prev_samples <- ncol(prevotella.df)
  #Logic has one cases: 
  #1.number of samples in tpm.df which have tpm > inp_threshold is 
  #greater than number of samples * inp_prevalence AND locus does not match PREVOTELLA_ROW_RE 
  # genes_passing <- rownames(data.frame(logic = ((rowSums(tpm.df > inp_threshold) > num_samples*inp_prevalence) | (rowSums(prevotella.df > inp_threshold) >num_prev_samples*inp_prevalence & (grepl(PREVOTELLA_ROW_RE, row.names(tpm.df)))))) %>% filter(logic == TRUE))
    genes_passing <- rownames(data.frame(logic = ((rowSums(tpm.df > inp_threshold) > num_samples*inp_prevalence) & !(grepl(PREVOTELLA_ROW_RE, row.names(tpm.df))))) %>% filter(logic==TRUE))
  return(genes_passing)
}
```

```{r}
# inp_threshold = 5 #Steven MAG default
# inp_prevalence = 0.4 #Steven MAG default 
inp_threshold = 3
inp_prevalence = 0.25
CECAL_ONLY = TRUE
FILTER_SPEC = "nonprevotella"

#Dir Path for filtered datasets given parameter settings 
if (CECAL_ONLY) {
  sample_flag = "cecal"
} else {
  sample_flag = "all"
}
param_str <- sprintf("thr%s_prev%s_%s_%s",inp_threshold,inp_prevalence,sample_flag,FILTER_SPEC)
filt_param_dir <-  sprintf("formatted_output/4th_trial/transformed_abundance_corrected/%s_%s",param_str,AC_tag)
filt_param_dir_path <-file.path(getwd(),filt_param_dir) 
dir.create(filt_param_dir_path,showWarnings = FALSE)

filt_vst_fpath = sprintf("%s/filt_merged_vst.csv",filt_param_dir_path)
filt_rlog_fpath = sprintf("%s/filt_merged_rlog.csv",filt_param_dir_path)
filt_log_fpath = sprintf("%s/filt_merged_log.csv",filt_param_dir_path)
filt_tpm_fpath = sprintf("%s/filt_merged_tpm.csv",filt_param_dir_path)
filt_counts_fpath = sprintf("%s/filt_merged_count.csv",filt_param_dir_path)


FORCE_RECALC = FALSE
if (file.exists(filt_vst_fpath) & ! FORCE_RECALC) {
  #Read existing data from fpaths 
  filt_vst.df <- read.csv(filt_vst_fpath,row.names=1)
  filt_log.df <- read.csv(filt_log_fpath,row.names=1)
  filt_rlog.df <- read.csv(filt_rlog_fpath,row.names=1)
  filt_tpm.df <-read.csv(filt_tpm_fpath,row.names=1)
} else {
  #Generate filtered gene vector using above tpm/prevalence thresholds and  whether or not to use cecal samples only for thresholding
  prev_filt_genes.vec <- get_prevotella_filtered_gene_vec(tpm.df,inp_threshold,inp_prevalence,CECAL_ONLY = CECAL_ONLY)
  nonprev_filt_genes.vec <- get_non_prevotella_filtered_gene_vec(tpm.df,inp_threshold,inp_prevalence,CECAL_ONLY = CECAL_ONLY)
  if (FILTER_SPEC=="nonprevotella") {
    filt_genes.vec <- nonprev_filt_genes.vec
  }
  else if (FILTER_SPEC=="prevotella") {
    filt_genes.vec <- prev_filt_genes.vec
  }
  
  length(filt_genes.vec)
  mc_int_filt.df <- merged_counts_int.df[rownames(merged_counts_int.df) %in% filt_genes.vec,]
  mc_num_filt.df <- merged_counts_num.df[rownames(merged_counts_num.df) %in% filt_genes.vec,]
  filt_tpm.df <- tpm.df[rownames(tpm.df) %in% filt_genes.vec,]
  
  #Filter to only cecal contents columns - mc_int_filt, mc_num_filt
  if (CECAL_ONLY) {
    CECAL_COL_RE = "cecal"
    cecal_samples <- grep(CECAL_COL_RE, colnames(filt_tpm.df)) 
    filt_tpm.df <- dplyr::select(filt_tpm.df,cecal_samples)
    mc_int_filt.df <- dplyr::select(mc_int_filt.df,cecal_samples)
    mc_num_filt.df <-dplyr::select(mc_num_filt.df,cecal_samples)
  }
  
  #Generate transformed dataframes 
  #vst and log of filtered dfs
  mc_filt_matrix <- data.matrix(mc_int_filt.df)
  mode(mc_filt_matrix) <- "integer"
  filt_vst.df <- as.data.frame(vst(mc_filt_matrix)) #parametric fitType fails and forces local regression
  filt_rlog.df <-as.data.frame(rlog(mc_filt_matrix))
  filt_log.df <- as.data.frame(log(data.matrix(mc_num_filt.df) + PSEUDOCOUNT))
  #Write filtered dataframes to csv 
  write.csv(filt_vst.df,filt_vst_fpath,quote=FALSE)
  write.csv(filt_rlog.df,filt_rlog_fpath,quote=FALSE)
  write.csv(filt_log.df,filt_log_fpath,quote=FALSE)
  write.csv(filt_tpm.df,filt_tpm_fpath,quote=FALSE)
  write.csv(mc_int_filt.df,filt_counts_fpath,quote=FALSE)
}

```

```{r}
###============###
#Use EdgeR filtered AC counts for input into rlog 
###============###
edgeR_filtered_dir = "formatted_output/4th_trial/edgeR_filtered"
edgeR_filtered_AC_int_fpath = sprintf("%s/edgeR_filt_AC.csv",edgeR_filtered_dir)
edgeR_filt_AC.df <- read.csv(edgeR_filtered_AC_int_fpath,row.names="target_id")
edgeR_filt_AC_int_matrix <- data.matrix(edgeR_filt_AC.df)
mode(edgeR_filt_AC_int_matrix) <- "integer" 
edgeR_filt_rlog.df <-as.data.frame(rlog(edgeR_filt_AC_int_matrix))

edgeR_rlog_fpath = sprintf("%s/edgeR_filt_rlog.csv",edgeR_filtered_dir)
write.csv(edgeR_filt_rlog.df,edgeR_rlog_fpath,quote=FALSE)
```
